### ISSUE TITLE
Expansion crash at start.  

### ISSUE THREAD

**Issue by PhantomTrackmania** [Skorlok/eXpansion#1]
Hello.

Was trying out your work but somehow it won't start.
I made a screeny , maybe you can help out.

![expansion-crash](https://github.com/Skorlok/eXpansion/assets/139126997/e88bdca0-0c64-40bd-b37f-93104f959f82)

**Comment by Skorlok** [comment]
Yo,

I fixed that issue, you just need to open a terminal in the eXpansion folder and type `PATH/TO/YOUR/PHP.exe composer update`

it was because I used some new function that works only on php8+

**Comment by Skorlok** [comment]
Or use the **update.bat** script (be sure to edit it to set your php path)

at the question `Do you wish to install for development [y/n]?:` the 2 options does the same thing
