### ISSUE TITLE
Some widgets are overlapping.

### ISSUE THREAD

**Issue by PhantomTrackmania** [Skorlok/eXpansion#2]
I have some widgets at the wrong place.
I think those widgets come with de maniaplanet server.
But on your server those widgets are on a different place.
I made a screeny :  
![EXPANSION-timer](https://github.com/Skorlok/eXpansion/assets/139126997/d7834955-52dc-4cfd-bb35-2a63c54812c7)

The red arrow points at all wrong widgets.

**Comment by Skorlok** [comment]
These widgets are the default ones from the maniaplanet server
I made a plugin to change this
![image](https://github.com/Skorlok/eXpansion/assets/70608768/f0edd468-5e9e-44c5-af03-a9ed00ac2d42)
just enable it and it will fix
