### ISSUE TITLE
Some problems with matchsettings file

### ISSUE THREAD

**Issue by PhantomTrackmania** [Skorlok/eXpansion#3]
I wanted to save the matchsettings file , but returned into errors.
Screeny :  

![expansion utf8 errr](https://github.com/Skorlok/eXpansion/assets/139126997/b7b5256c-be4b-4226-8b28-c63947c2b394)

Log : 

[manialive-error.log](https://github.com/Skorlok/eXpansion/files/12401864/manialive-error.log)

I also noticed when opening the matchsettings ( in menu ) there is nothing there. I also can not load any.
There should be at least one matchsetting otherwise the server won't start.
Screeny : 

![expansion matchsettings file](https://github.com/Skorlok/eXpansion/assets/139126997/6b0ff9d3-77e8-40e9-81cd-adaf3d6d975e)

I hope I don't cause you to much trouble. But your budy was so exited about this controller so I would give it a try. But I could not find much documentation about it.

**Comment by Skorlok** [comment]
eXpansion are currently not supporting php8.2, for instant only version between 5.50 and 8.1.22 is supported

At every new update php get something deprecated, this issue will not be fixed right now

you can try with your php7.2 or for better performance try with 8.1

that true, for instant I have not doc

**Comment by PhantomTrackmania** [comment]
Ah , ok. 
Thanks for support.

**Comment by PhantomTrackmania** [comment]
Ok, I'm back to php 8.1  , all seems to work fine.
Thanks again ^^

**Comment by PhantomTrackmania** [comment]
Oops , some new problems.

![expansion- map error](https://github.com/Skorlok/eXpansion/assets/139126997/e9bdc91c-2cb4-4601-b3cc-fa2a8c8ba489)

[manialive-canyon40.console.log](https://github.com/Skorlok/eXpansion/files/12412576/manialive-canyon40.console.log)

**Comment by Skorlok** [comment]
It seems eXpansion is unable to read GBX map files

What did you do before getting these errors ?

**Comment by PhantomTrackmania** [comment]
Well, I removed xampp and installed an older version.  I went from php 8.2 to php 8.1

Nothing else that I can think of.

**Comment by PhantomTrackmania** [comment]
It has to do with the new install of php 8.1
I always use UniServer Zero for Uaseco.  This has php 7.2.22 and expansion runs fine on that.
So what could be wrong with php8.1 ? I guess you are also running php 8 +

**Comment by PhantomTrackmania** [comment]
![expansion php 8 1](https://github.com/Skorlok/eXpansion/assets/139126997/d598a068-85e3-4f72-96ee-8a5c569b83a5)

That error I screaned , by klicking the mapname at the top right of the screen , occurs at every map.  So its not a map thing.
Could it be a read / write right.

**Comment by Skorlok** [comment]
I think it's a read right problem, eXpansion found the map, but somehow it cannot read/parse it
but it's really weird on windows

if it works well with php7.2 use it, eXpansion will work same

**Comment by PhantomTrackmania** [comment]
Update :  

I installed php 8.0.28 and it seems to run fine now.  No errors after klicking map name top right of the screen.
Can also load map from MX. So I stay with this version I guess.

**Comment by Skorlok** [comment]
ok, really weird, I can't reproduce this bug

I still have a working PHP8.1 [https://cdn.skorlok.com/file/php8.1.zip](url)

version doesn't really matter, eXpansion works same on 5.5 that on 7.4

**Comment by PhantomTrackmania** [comment]
Realy strange.
Anyway , it runs now fine.  Thanks for your support so far, realy nice that you took some time to help out.
Topic close ?   :)
